package com.braja.rxjava.util.constant;

import lombok.Getter;

@Getter
public enum IsoDataElement {
    MESSAGE_TYPE_INDICATOR(0),
    BIT_MAP(1),
    PRIMARY_ACCOUNT_NUMBER(2),
    PROCESSING_CODE(3),
    TRANSACTION_AMOUNT(4),
    TRANSMISSION_DATE_AND_TIME(7),
    SYSTEM_TRACE_AUDIT_NUMBER(11),
    LOCAL_TRANSACTION_TIME(12),
    LOCAL_TRANSACTION_DATE(13),
    SETTLEMENT_DATE(15),
    CAPTURE_DATE(17),
    MERCHANTS_TYPE(18),
    POINT_OF_SERVICE_ENTRY_MODE(22),
    TRANSACTION_FEE_AMOUNT(28),
    ACQUIRING_INSTITUTION_IDENT_CODE(32),
    FORWARDING_INSTITUTION_IDENT_CODE(33),
    RETRIEVAL_REFERENCE_NUMBER(37),
    AUTHORIZATION_IDENTIFICATION_RESPONSE(38),
    RESPONSE_CODE(39),
    CARD_ACCEPTOR_TERMINAL_IDENTIFICACION(41),
    CARD_ACCEPTOR_IDENTIFICATION_CODE(42),
    CARD_ACCEPTOR_NAME_LOCATION(43),
    ADITIONAL_DATA_PRIVATE(48),
    TRANSACTION_CURRENCY_CODE(49),
    NETWORK_MANAGEMENT_INFORMATION_CODE(70),
    ORIGINAL_DATA_ELEMENTS(90),
    RECEIVING_INSTITUTION_IDENT_CODE(100),
    ACCOUNT_IDENTIFICATION_1(102),
    INVOICE_NUMBER(123),
    MAC_2(128);

    private Integer id;

    IsoDataElement(Integer id){
        this.id = id;
    }
}
